[package]
name = "ossm-example-headers-extension"
version = "1.0.0"
authors = ["Ignacio Sanchez <isanchez@redhat.com>"]
edition = "2018"

[dependencies]
proxy-wasm = "0.1.3"
serde_json = "1.0.62"
log = "0.4"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"
